services:
  backend:
    build: backend/
    env_file:
      - backend/.env
    ports:
      - "8000:8000" 
  frontend:
  # image: frontend-npm
    build: frontend/
    stdin_open: true
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
    - "./frontend:/usr/src/app:delegated"
    - /app/node_modules/
    working_dir: /usr/src/app
    tty: true
