# Generated by Django 5.2 on 2025-05-08 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_rename_parent_response_comment_response_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='question',
        ),
    ]
